export const PROFILE_MISSION = {
  ar: "تمكين الشباب السوري فكرياً وثقافياً وقيادياً، وبناء قدراتهم، وتوسيع مشاركتهم في الشأن العام، ليكونوا شركاء فاعلين في بناء سوريا.",
  en: "To empower Syrian youth intellectually, culturally, and in leadership; to build their capacities; and to expand their participation in public affairs, so they become active partners in building Syria.",
};

export const PROFILE_VISION = {
  ar: "أن نكون المؤسسة الشبابية الرائدة في سوريا، نصنع جيلاً يحوّل طاقته إلى أثر، ووعيه إلى فعل، وانتماءه إلى بناء.",
  en: "To be the leading youth organization in Syria, fostering a generation that transforms its energy into impact, its awareness into action, and its sense of belonging into constructive contribution.",
};

export const PROFILE_SLOGAN = {
  ar: "جيلٌ شابٌ متمكنٌ وقوي.",
  en: "An empowered and strong youth generation.",
};

export const PROFILE_STORY = {
  ar: "في لحظة فارقة من عمر سوريا، لم يكن السؤال: ماذا حدث؟ بل: ماذا بعد؟ ومن هذا السؤال وُلدت مؤسسة الشباب السوري. لم نبدأ من مكتب فخم، بدأنا من قناعة أن في الشاب السوري طاقة تنتظر من يفتح لها الباب. جمعنا الشباب ليكون لهذا الجيل بيت يحتضنه، ومساحة يكبر فيها، وصوت يُسمع. امتد العمل من دمشق إلى حلب، ومن الساحل إلى الجزيرة، حتى صارت شبكة تنهض في عشر محافظات. آمنا أن الشباب ليسوا مشكلة تُدار، بل طاقة تُوجَّه، وأنهم حاضر يصنع الآن. فلم نعلّمهم ماذا يفكرون، بل كيف يفكرون. نحن وعد لهذا الجيل: أن نمضي معه من اليافعة إلى القيادة، ومن الحلم إلى الأثر، ومن الانتماء إلى البناء.",
  en: "At a turning point in Syria's life, the question was not what happened, but what comes next. From that question the Syrian Youth Foundation was born. We did not start from a grand office. We started from the conviction that Syrian youth hold energy waiting for a door to open. We gathered young people so this generation would have a home, room to grow, and a voice that is heard. The work spread from Damascus to Aleppo, and from the coast to the Jazira, until it became a network across ten governorates. We believe youth are not a problem to be managed, but energy to be directed — a present that is being made now. We do not teach them what to think. We teach them how to think. We are a promise to walk with this generation from adolescence to leadership, from dream to impact, and from belonging to building.",
};

export const PROFILE_PRINCIPLES = [
  {
    ar: "الوطنية الجامعة: المؤسسة لكل الشباب السوري، وتعلو فوق الانقسامات المناطقية والطائفية.",
    en: "Inclusive patriotism: the Foundation is for every Syrian young person, above regional and sectarian division.",
  },
  {
    ar: "الاستقلالية: القرار والمحتوى والبرامج تُصنع داخل المؤسسة. الجهات الرسمية تمكين، لا تبعية.",
    en: "Independence: decisions, content, and programs are made inside the Foundation. Official bodies enable the work; they do not own it.",
  },
  {
    ar: "اللاحزبية: لا انتماء حزبي ولا توظيف ضيق. البناء للإنسان، لا لحشد الأنصار.",
    en: "Non-partisanship: no party affiliation and no narrow instrumentalization. The work builds people, not followings.",
  },
  {
    ar: "القيمة قبل الشعار: نمارس قيمنا ولا نتاجر بها، ونثبتها بالفعل لا بالادعاء.",
    en: "Values before slogans: we practice our values, we do not trade on them, and we prove them by action.",
  },
  {
    ar: "الأصالة والمعاصرة: نجمع بين رسوخ الهوية وانفتاح الأدوات.",
    en: "Authenticity and the present: we hold a rooted identity and open tools together.",
  },
  {
    ar: "الأثر لا النشاط: نقيس أنفسنا بما نحدثه من تغيير، لا بعدد الفعاليات.",
    en: "Impact, not activity: we measure ourselves by the change we make, not by the number of events.",
  },
];

export const PROFILE_VALUE_NOTES = [
  {
    ar: "الكرامة",
    en: "Dignity",
    noteAr: "لكل إنسان قيمة أصيلة تُصان، بغض النظر عن خلفيته أو موقعه.",
    noteEn: "Every person holds an inherent worth that must be protected, regardless of background or position.",
  },
  {
    ar: "المسؤولية",
    en: "Responsibility",
    noteAr: "الحرية لا تنفصل عن تبعتها. نحاسب أنفسنا قبل أن يحاسبنا أحد.",
    noteEn: "Freedom is inseparable from accountability. We hold ourselves to account before anyone else does.",
  },
  {
    ar: "العدل",
    en: "Justice",
    noteAr: "إنصاف الناس أساس كل عمران. لا تمييز على أساس انتماء أو موقع.",
    noteEn: "Fairness is the basis of anything we build. We do not discriminate by affiliation or status.",
  },
  {
    ar: "الأمانة",
    en: "Integrity",
    noteAr: "الصدق شرط أي بناء يدوم. نقول ما نفعل، ونفعل ما نقول.",
    noteEn: "Honesty is the condition for anything built to last. We say what we do, and do what we say.",
  },
  {
    ar: "الإحسان",
    en: "Excellence",
    noteAr: "إحسان العمل قيمة في ذاته، لا وسيلة لغاية.",
    noteEn: "Doing the work well is a value in itself, not merely a means to an end.",
  },
  {
    ar: "الانتماء",
    en: "Belonging",
    noteAr: "الفرد لا يكتمل إلا في وطن يعمل لرفعته. الجذور قبل الجناح.",
    noteEn: "A person is complete only within a homeland they work to elevate. Roots before flight.",
  },
  {
    ar: "التكافل",
    en: "Solidarity",
    noteAr: "المجتمع جسد واحد. لا نهضة فردية بمعزل عن نهضة الجماعة.",
    noteEn: "Society is one body. There is no individual rise apart from the rise of the collective.",
  },
];

export const ACTIVE_GOVERNORATES = [
  { ar: "دمشق", en: "Damascus", hub: true },
  { ar: "ريف دمشق", en: "Rural Damascus", hub: false },
  { ar: "حلب", en: "Aleppo", hub: false },
  { ar: "حمص", en: "Homs", hub: false },
  { ar: "حماة", en: "Hama", hub: false },
  { ar: "اللاذقية", en: "Latakia", hub: false },
  { ar: "طرطوس", en: "Tartus", hub: false },
  { ar: "إدلب", en: "Idlib", hub: false },
  { ar: "درعا", en: "Daraa", hub: false },
  { ar: "القنيطرة", en: "Quneitra", hub: false },
  { ar: "دير الزور", en: "Deir ez-Zor", hub: false },
];

export const PROFILE_FOCUS_AREAS = [
  {
    id: "focus-1",
    icon: "leadership",
    titleAr: "الفكري والوعي",
    titleEn: "Thought and awareness",
    descriptionAr: "التفكير النقدي والحصانة الفكرية، وجعل المؤسسة بيتاً للفكر يحمل رؤية نهضوية.",
    descriptionEn: "Critical thinking and intellectual resilience, making the Foundation a home for thought with a renaissance vision.",
    imageUrl: "/images/hero/homs-youth.webp",
    sortOrder: 1,
  },
  {
    id: "focus-2",
    icon: "community",
    titleAr: "الثقافي والفني والإبداعي",
    titleEn: "Culture, art, and creativity",
    descriptionAr: "تعزيز الهوية الثقافية، وتنمية الذائقة، وصناعة المحتوى الأصيل.",
    descriptionEn: "Strengthening cultural identity, cultivating taste, and creating authentic content.",
    imageUrl: "/images/hero/ramadan-session.webp",
    sortOrder: 2,
  },
  {
    id: "focus-3",
    icon: "initiatives",
    titleAr: "الابتكاري والريادي",
    titleEn: "Initiative and entrepreneurship",
    descriptionAr: "تحفيز المبادرة وريادة الأعمال، وتحويل الأفكار إلى مشاريع.",
    descriptionEn: "Fostering initiative and entrepreneurship, and turning ideas into projects.",
    imageUrl: "/videos/hero-poster.jpg",
    sortOrder: 3,
  },
  {
    id: "focus-4",
    icon: "leadership",
    titleAr: "القيادي والمشارك في الشأن العام",
    titleEn: "Leadership and public affairs",
    descriptionAr: "إعداد القادة وتمثيل صوت الشباب ضمن الأطر الوطنية، بعيداً عن الحزبية.",
    descriptionEn: "Preparing leaders and representing the voice of youth within national frameworks, free from partisanship.",
    imageUrl: "/images/hero/ramadan-session.webp",
    sortOrder: 4,
  },
  {
    id: "focus-5",
    icon: "skills",
    titleAr: "المهاري والتنموي",
    titleEn: "Skills and development",
    descriptionAr: "بناء القدرات والمهارات العملية والحياتية.",
    descriptionEn: "Building capacities and practical and life skills.",
    imageUrl: "/images/hero/homs-youth.webp",
    sortOrder: 5,
  },
];

export const PROFILE_PROGRAMS = [
  {
    id: "program-qaid",
    slug: "qaid",
    icon: "leadership" as const,
    titleAr: "قائد",
    titleEn: "Qa'id (Leader)",
    descriptionAr: "برنامج إعداد القيادات الشابة. يبني مهارات القيادة والمبادرة ويؤهّل الشباب لقيادة التغيير في مجتمعاتهم.",
    descriptionEn: "A youth leadership program that builds leadership and initiative skills, preparing young people to lead change in their communities.",
    audienceAr: "شباب يريدون قيادة تغيير حقيقي في مجتمعهم.",
    audienceEn: "Young people who want to lead real change in their community.",
    scheduleAr: "مسار إعداد قيادي. يُعلن موعد كل دفعة عبر الأخبار وصفحة الفعاليات.",
    scheduleEn: "A leadership track. Each cohort's dates are announced in news and on the events page.",
    whereAr: "الفروع المحافظاتية، ودمشق مركزاً.",
    whereEn: "Governorate branches, with Damascus as the hub.",
    outcomesAr: "مهارات قيادة ومبادرة. أعدّ البرنامج أكثر من 400 قائد.",
    outcomesEn: "Leadership and initiative skills. More than 400 leaders have been trained.",
    sortOrder: 1,
  },
  {
    id: "program-mahattat",
    slug: "mahattat",
    icon: "skills" as const,
    titleAr: "محطات",
    titleEn: "Mahattat (Stations)",
    descriptionAr: "برنامج فكري ومهاري يعالج تساؤلات الشباب المعاصرة، وينمّي وعيهم وحصانتهم الفكرية عبر محطات متدرجة.",
    descriptionEn: "An intellectual and skills program that takes up young people's contemporary questions and builds awareness and critical resilience through progressive stations.",
    audienceAr: "شباب يبحثون عن أدوات للتفكير، لا عن شعار جاهز.",
    audienceEn: "Young people looking for tools to think, not a ready-made slogan.",
    scheduleAr: "محطات متدرجة. يمكن الانضمام من أي فرع تعلن عن محطة جديدة.",
    scheduleEn: "Progressive stations. Join from any branch that opens a new station.",
    whereAr: "فروع المؤسسة في المحافظات.",
    whereEn: "Foundation branches in the governorates.",
    outcomesAr: "وعي أوضح وحصانة فكرية، مع مهارة طرح السؤال قبل الجواب.",
    outcomesEn: "Clearer awareness and intellectual resilience, with the skill of asking before answering.",
    sortOrder: 2,
  },
  {
    id: "program-academic-path",
    slug: "academic-path",
    icon: "initiatives" as const,
    titleAr: "وجهتك الأكاديمية",
    titleEn: "Your Academic Path",
    descriptionAr: "ملتقى إرشاد أكاديمي يوجّه الطلبة المقبلين على الجامعة نحو اختيار تخصصهم بوعي، عبر التعريف بالاختصاصات من أهلها.",
    descriptionEn: "An academic guidance forum that helps pre-university students choose a major with care, by introducing disciplines through people who study them.",
    audienceAr: "طلبة في المرحلة الثانوية ومن هم على عتبة الجامعة.",
    audienceEn: "Secondary students and young people about to enter university.",
    scheduleAr: "ملتقيات دورية حسب الفرع. راقب صفحة الفعاليات لموعد الملتقى القادم.",
    scheduleEn: "Forums run by branch. Watch the events page for the next gathering.",
    whereAr: "حسب الفرع الذي يستضيف الملتقى.",
    whereEn: "Whichever branch is hosting the forum.",
    outcomesAr: "اختيار تخصص عن معرفة، بعد لقاء من يدرسونه ويعملون به.",
    outcomesEn: "A major chosen with knowledge, after meeting people who study and practice it.",
    sortOrder: 3,
  },
  {
    id: "program-adolescents",
    slug: "adolescents-club",
    icon: "volunteer" as const,
    titleAr: "نادي اليافعين",
    titleEn: "Adolescents' Club",
    descriptionAr: "مساحة آمنة لليافعين تبني وعيهم وشخصيتهم مبكراً عبر أنشطة تربوية وثقافية وترفيهية، وتكتشف مواهبهم وتنمّيها ضمن ضوابط حماية الطفل.",
    descriptionEn: "A safe space for adolescents that builds early awareness and character through educational, cultural, and recreational activities, and nurtures talent within child-protection safeguards.",
    audienceAr: "اليافعون، بموافقة ولي الأمر وعلم الفرع.",
    audienceEn: "Adolescents, with a guardian's consent and the branch's knowledge.",
    scheduleAr: "أنشطة منتظمة داخل النادي. ليست فعالية عابرة.",
    scheduleEn: "Regular club activities, not a one-off event.",
    whereAr: "منها طرطوس، ويمتد مع الفروع التي تفتتح النادي.",
    whereEn: "Including Tartus, and any branch that opens the club.",
    outcomesAr: "وعي وشخصية مبكرة، ومواهب تُكتشف داخل ضوابط حماية واضحة.",
    outcomesEn: "Early awareness and character, and talents discovered inside clear protection rules.",
    sortOrder: 4,
  },
  {
    id: "program-trainings",
    slug: "trainings",
    icon: "skills" as const,
    titleAr: "التدريبات المتنوعة",
    titleEn: "Diverse Trainings",
    descriptionAr: "منظومة تدريبات في المهارات الحياتية والقيادية والمهنية والرقمية، لبناء قدرات الشباب وتأهيلهم لسوق العمل والحياة العامة.",
    descriptionEn: "Trainings in life, leadership, professional, and digital skills that build capacity for work and public life.",
    audienceAr: "شباب يريدون مهارة يمكن استخدامها، لا شهادة تُعلَّق.",
    audienceEn: "Young people who want a skill they can use, not a certificate to hang.",
    scheduleAr: "دورات قصيرة يعلنها كل فرع. المدة والمقاعد في صفحة الفعالية.",
    scheduleEn: "Short courses announced by each branch. Duration and seats are on the event page.",
    whereAr: "في المحافظة التي تستضيف الدورة.",
    whereEn: "In the governorate hosting the course.",
    outcomesAr: "مهارة حياتية أو مهنية أو رقمية يمكن البناء عليها.",
    outcomesEn: "A life, professional, or digital skill to build on.",
    sortOrder: 5,
  },
  {
    id: "program-public-events",
    slug: "public-events",
    icon: "initiatives" as const,
    titleAr: "الفعاليات الجماهيرية",
    titleEn: "Public Events",
    descriptionAr: "فعاليات كبرى ومشاركات مجتمعية تجمع الشباب حول قضاياهم وهويتهم، وتعزز حضور المؤسسة وأثرها في المحافظات.",
    descriptionEn: "Major public events and wide community participation that bring young people together around their causes and identity.",
    audienceAr: "الشباب والمجتمع المحلي في المحافظة المستضيفة.",
    audienceEn: "Youth and the local community in the host governorate.",
    scheduleAr: "حسب الإعلان. التاريخ والمدينة يُنشران في صفحة الفعاليات.",
    scheduleEn: "As announced. Date and city are published on the events page.",
    whereAr: "في المحافظات التي تقام فيها الفعالية.",
    whereEn: "In the governorates where the event is held.",
    outcomesAr: "مشاركة أوسع، وحضور للشباب في الشأن العام.",
    outcomesEn: "Wider participation, and a public presence for youth.",
    sortOrder: 6,
  },
];

export const PROFILE_IMPACT_STATS = [
  {
    id: "stat-1",
    labelAr: "متطوع",
    labelEn: "Volunteers",
    value: "1,500+",
    noteAr: "شبكة التطوع المفتوح عبر الفروع.",
    noteEn: "The open volunteer network across branches.",
    icon: "users",
    sortOrder: 1,
  },
  {
    id: "stat-2",
    labelAr: "شاب وصلهم العمل",
    labelEn: "Youth reached",
    value: "500,000+",
    noteAr: "منذ التأسيس، وفق الملف التعريفي للمؤسسة.",
    noteEn: "Since founding, as stated in the institutional profile.",
    icon: "heart",
    sortOrder: 2,
  },
  {
    id: "stat-3",
    labelAr: "محافظات",
    labelEn: "Governorates",
    value: "10",
    noteAr: "حضور فاعل، ودمشق مركزاً.",
    noteEn: "An active presence, with Damascus as the hub.",
    icon: "map",
    sortOrder: 3,
  },
  {
    id: "stat-4",
    labelAr: "قائد أُعدّ",
    labelEn: "Leaders trained",
    value: "400+",
    noteAr: "خرّيجو برنامج قائد.",
    noteEn: "Graduates of the Qa'id program.",
    icon: "users",
    sortOrder: 4,
  },
];

export const FALLBACK_EVENTS = [
  {
    id: "event-mahattat",
    slug: "mahattat-stations",
    titleAr: "محطات فكرية",
    titleEn: "Mahattat stations",
    descriptionAr: "محطات متدرجة للوعي والحصانة الفكرية. التسجيل عبر طلب الانضمام إلى البرنامج.",
    descriptionEn: "Progressive stations for awareness and intellectual resilience. Register through the program form.",
    cityAr: "فروع المحافظات",
    cityEn: "Governorate branches",
    startsAt: null as string | null,
    isRolling: true,
    registerPath: "/get-involved?program=محطات#program",
    imageUrl: "/images/hero/ramadan-session.webp",
  },
  {
    id: "event-adolescents",
    slug: "adolescents-club-tartus",
    titleAr: "نادي اليافعين",
    titleEn: "Adolescents' Club",
    descriptionAr: "مساحة منتظمة لليافعين ضمن ضوابط حماية الطفل. منها التجربة المفتتحة في طرطوس.",
    descriptionEn: "A regular space for adolescents under child-protection safeguards, including the club opened in Tartus.",
    cityAr: "طرطوس والفروع",
    cityEn: "Tartus and other branches",
    startsAt: null as string | null,
    isRolling: true,
    registerPath: "/get-involved?program=نادي اليافعين#program",
    imageUrl: "/images/hero/homs-youth.webp",
  },
  {
    id: "event-academic",
    slug: "academic-path-forum",
    titleAr: "ملتقى وجهتك الأكاديمية",
    titleEn: "Your Academic Path forum",
    descriptionAr: "تعريف بالاختصاصات من أهلها للطلبة المقبلين على الجامعة.",
    descriptionEn: "Disciplines introduced by the people who study them, for students about to enter university.",
    cityAr: "حسب الفرع المستضيف",
    cityEn: "Host branch",
    startsAt: null as string | null,
    isRolling: true,
    registerPath: "/get-involved?program=وجهتك الأكاديمية#program",
    imageUrl: "/videos/hero-poster.jpg",
  },
];
